### PR TITLE
Pull request: Mengfan dev

### PR DESCRIPTION
**Pull request by DEUCE1957**
Base provision (no new code).
Plan:
1. Setup Jupyter environment
2. Import Matrix data (from .mat or .csv files)
3. Train (for 1 epoch) an MA-DDPG agent to validate codebase is running
4. (Optional) Setup Azure to fully train agent
5. Develop GUI interface (e.g. in PyQt5)

### CODE REVIEW

**Comment by babreu-ncsa** [comment]
Hi @DEUCE1957, I see you marked me as a reviewer. Is there any particular issue that you would like me to take a look at?

**Comment by DEUCE1957** [comment]
@babreu-ncsa Not at the moment, apologies must have accidentally hit a wrong button.

**Comment by DEUCE1957** [comment]
From this point onwards the "MADDPG_basic.ipynb" notebook in "research_teams/xu/" directory is writable. Next step is to load in the data.

**Comment by babreu-ncsa** [comment]
@DEUCE1957 are you still developing this package? This training cluster is going to phase out soon, if you are still developing we should think about a migration strategy.

**Comment by babreu-ncsa** [comment]
Closing this PR for inactivity.

**Pull request closed without merging**
