### PR TITLE
add a bunch of observation processing files

### PR DESCRIPTION
**Pull request by hgordo**
these are highly unlikely to work but it's a start...

### CODE REVIEW

**Comment by hgordo** [comment]
@babreu-ncsa  hi Bruno,
I had a go at making some containers for processing observations along the same lines as the model data. ObservationSet is meant to correspond to SimulationSample, but actually I haven't properly understood what SimulationSample does, so I think this bit is especially likely to be very wrong. I have run out of time for this today but if you could have a quick look and come up with a few tips for how to proceed I'd be grateful, if not I'll have a go at debugging it myself, most likely early next week. Many thanks for your help!

**Comment by babreu-ncsa** [comment]
@hgordo hi Hamish, thanks for giving this a try! It looks like you got most of it right, it is complaining about one of the fields in your ObservationSet type... I'm taking look at this

**Comment by babreu-ncsa** [comment]
@hgordo Alright, it looks like it worked. I had to add the **observationSet** key to the ObservationOutputFile type, from which the collection field **outputFiles** of the ObservationSet type gets filtered and populated... Everything else looks good to me

**Comment by hgordo** [comment]
@babreu-ncsa many thanks and have a good weekend!

**Comment by hgordo** [comment]
@babreu-ncsa Hi Bruno, I had a go in the above commits at actually making the observation data upsertable, having created the structures for it before. My new code provisions, but I haven't actually managed to upsert the data. I tried running a batch job "upsertObsData", which submitted and ran for (I think) at least half an hour, but I had to restart my computer before it finished, so I don't know how to retrieve the status of it, and the c3Grid(ObservationOutput.fetch()) command unsurprisingly gives me an empty table. If you can have a look that would be awesome! Many thanks. Hamish

**Comment by babreu-ncsa** [comment]
Closing this PR and opening a new one to test ObservationSet seeded data

**Pull request closed without merging**
