### PR TITLE
ingest Observation data

### PR DESCRIPTION
**Pull request by babreu-ncsa**

### CODE REVIEW

**Comment by babreu-ncsa** [comment]
There was a Transform type missing to connect the ObservationSet objects to their associated timeseries (TransformSourceObservationSetToObservationOutputSeries). This gets me one Timeseries instance associated to this ObservationSet (mrg_P3 version R26):

image

Now I'm gonna test the upsertORACLEData method in the ObservationOutputFile type

**Comment by babreu-ncsa** [comment]
This gives me an error when upserting the entire batch... not sure what it is. I'm going to do all the steps in ObservationOutputFile.py in a notebook

**Comment by babreu-ncsa** [comment]
The last commit takes care of populating ObservationOutput with data at the file level (see for instance this [Jupyter notebook](https://tc02d-dev.c3dti.ai/jupyter/notebooks/research_teams/gordon/upsert-observation-data.ipynb#)). Here's how they look:

image

**Next steps**:
- Test the batch job upsert workflow
- Create EvalMetrics to populate the timeseries

**Comment by babreu-ncsa** [comment]
This takes care of all the files in the blob. ObservationOutputFile.upsertORACLESData() works.

image

image

Now moving to test ObservationSet.upsertObservationData()

**Comment by babreu-ncsa** [comment]
HI @hgordo! It looks like everything is working with these methods. I'm able to upsert data for a single file, for an entire set, and for all files for all sets (this last one via a batch job). However, there's a little problem. For the mrg1_P3 version R26 files, some of them do not have the **rBC_massConc** variable, while some others do. This makes the job crash.
For instance:

image

The file is: *azure://aircraft-observations/mrg1_P3_20170802_R26.nc*
When I try to open it from a [notebook](https://tc02d-dev.c3dti.ai/jupyter/notebooks/research_teams/gordon/test-file-upsert.ipynb#), I get:

image

Let me know if you have any insights on how we should proceed

**Comment by babreu-ncsa** [comment]
Hi @hgordo! Okay, that sounds good. I'll add a try/except to the python method. Unfortunately, our clusters are down this morning. I'll get back to this issue as soon as service is restored.

**Comment by hgordo** [comment]
hi @babreu-ncsa , I tried to add some more variables and run a batch upsert, I guess it may well have failed because you are figuring out a way to avoid the problem of missing data, or I may have screwed something up. Hopefully I didn't overwrite any of your changes when I merged my local copy of the repository - I don't think I did but it's not impossible.  

I am also checking the consistency of the BC concentrations on 18 August 2017 are not consistent between the upserted total_BC and the BC in the netcdf file by comparing it between the bottom of the grab_multiple_members notebook and the open-aircraft-observation-files notebook. Not sure they are matching right now, but again that may be because of recent changes. I'd be interested to get your thoughts on that when you get the chance. Many thanks!
Hamish

**Comment by babreu-ncsa** [comment]
The workaround above seems to have worked with the file that would crash the jobs:

image

There's probably a better way to define that python class, but... it's working.
I'm going to clean the BatchQueue and start a new job to see if everything gets upserted.

**Comment by babreu-ncsa** [comment]
and by the way, here's a way to clean up jobs in the Batch Queue...

```
c3QReport(BatchQueue, true, true)
```

returns a list of the jobs that are pending in that queue. In the **targetType** column, we can see what is the Type that mixes in BatchJob, which is the one we need to fetch (in our case targetType could be, for instance, UpsertObsData):

```
var jobs = targetType.fetch().objs
```

then create a quick function to cancel them

```
function cancel(job) {
    job.cancel();
};
```

and then run it over all jobs:

```
jobs.forEach(cancel)
```

**Comment by babreu-ncsa** [comment]
The batch job ran in about 30 minutes, about half a million rows were upserted to the ObservationOutput table.
I'm checking on the timeseries now

**Comment by babreu-ncsa** [comment]
A quick check on the timeseries vs. file values seems  to indicate some degree of consistency:

image

image


I had to change a little bit the way the EvalMetrics was being performed to account for the same time interval that the file-based method covers (only 2017-08-18)

**Comment by babreu-ncsa** [comment]
Hi @hgordo! I think this PR covers the Observation data ingestion. We can discuss during our next meeting a better way to validate the timeseries data (having to switch between kernels is not ideal now). I'm closing this PR to propagate the changes to the other repos.

**Pull request merged**
