### PR TITLE
Add test for AOD data

### PR DESCRIPTION
**Pull request by babreu-ncsa**
Inconsistencies between Cassandra data `Simulation3HourlyAODOutput` and the NetCDF files were found.

### CODE REVIEW

**Comment by JamesCarzon** [comment]
@babreu-ncsa, This seems like a familiar problem I've caused again. Would you help me try to provision the reversion of my recent change?

I was hoping to add the `nbformat` module to the gordon_2_0_0 kernel. This is so I can call Notebooks from other Notebooks. (I would be working from base Python if I had access to the `cartopy` module from there. The base kernel does have `nbformat`.) However, I can't check its compatibility with the modules I have now without trying to add it and then reinstalling the kernel, which is somewhat time consuming. Is there another way of installing a module for use on the C3 server? For example, maybe one could install a module through a terminal from the Jupyter directory, but I don't have admin privileges for that.

**Comment by babreu-ncsa** [comment]
@JamesCarzon unfortunately there is not a direct way to install the package in the server, and debugging it when you add a package to the kernel is time-consuming if you go that route. There's a different approach, though. You can create a conda environment locally, in your machine, with the same Python version and the same packages versions that you have in your ActionRuntime that goes into c3. When you want to add a new package, you do a conda install locally, see what version of the package you get (conda will solve dependencies), and then check on the version that got installed, add that to the ActionRuntime, and then you know it will work. Let me do that for gordon_2_0_0 + nbformat and I'll post some screenshots here

**Comment by babreu-ncsa** [comment]
@JamesCarzon here's how it goes:

```
conda create -n gordon_2_0_0 python=3.6
```

```
conda activate gordon_2_0_0
```

```
conda install netcdf4=1.5.7 numpy=1.17.0 pandas=1.1.5 cartopy=0.18.0 basemap=1.2.2 iris=3.1.0 scikit-learn=0.23.1 dill=0.2.8.2
```

```
conda install nbformat
```

Then:

```
$ conda list
# packages in environment at /Users/babreu/opt/anaconda3/envs/gordon_2_0_0:
#
# Name                    Version                   Build  Channel
antlr-python-runtime      4.7.2           py36h79c6626_1002    conda-forge
basemap                   1.2.2            py36hd28bdb3_3    conda-forge
bleach                    5.0.0              pyhd8ed1ab_0    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.5.18.1          h033912b_0    conda-forge
cartopy                   0.18.0           py36h2b367c6_8    conda-forge
certifi                   2021.5.30        py36h79c6626_0    conda-forge
cf-units                  2.1.4            py36h962fabe_2    conda-forge
cftime                    1.5.0            py36he3068b8_0  
curl                      7.83.1               h372c54d_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dask-core                 2021.3.0           pyhd8ed1ab_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.2.8.2               py36_1000    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h96cf925_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
hdf4                      4.2.13            hefd3b78_1005    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
iris                      3.1.0              pyhd8ed1ab_3    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h5eb16cf_1    conda-forge
jsonschema                2.6.0                 py36_1002    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
kiwisolver                1.3.1            py36hc61eee1_1    conda-forge
krb5                      1.19.3               hb49756b_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libblas                   3.9.0           14_osx64_openblas    conda-forge
libcblas                  3.9.0           14_osx64_openblas    conda-forge
libcurl                   7.83.1               h372c54d_0    conda-forge
libcxx                    14.0.3               hc203e6f_0    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           14_osx64_openblas    conda-forge
libnetcdf                 4.6.1                hfd9a460_4  
libnghttp2                1.47.0               h942079c_0    conda-forge
libopenblas               0.3.20          openmp_hb3cd9ec_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.3.0                h17f2ce3_3    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libzlib                   1.2.11            h6c3fc93_1014    conda-forge
llvm-openmp               14.0.3               ha654fa7_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
markupsafe                2.0.1            py36hfa26744_0    conda-forge
matplotlib-base           3.2.2            py36h83d3ec1_1    conda-forge
mistune                   0.8.4           py36hfa26744_1004    conda-forge
nbconvert                 5.6.1              pyhd8ed1ab_2    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
netcdf4                   1.5.7            py36h1695cb1_0  
numpy                     1.17.0           py36h6b0580a_0    conda-forge
openssl                   1.1.1o               hfe4f2af_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.1.5            py36h2be6da3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
pip                       20.0.2                   py36_1    conda-forge
proj                      7.2.0                h78d1473_2    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.0.1            py36hd24fe16_0    conda-forge
pyshp                     2.3.0              pyhd8ed1ab_0    conda-forge
python                    3.6.15          haf480d7_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-xxhash             2.0.2            py36hfa26744_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py36hfa26744_1    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
scikit-learn              0.23.1           py36hef903b7_0    conda-forge
scipy                     1.5.3            py36h04de62b_0    conda-forge
setuptools                49.6.0           py36h79c6626_3    conda-forge
shapely                   1.7.1            py36h9a6d1a1_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.5               hd9f0692_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tornado                   6.1              py36hfa26744_1    conda-forge
traitlets                 4.3.3              pyhd8ed1ab_2    conda-forge
udunits2                  2.2.28               h06ef574_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xxhash                    0.8.0                h35c211d_3    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zlib                      1.2.11            h6c3fc93_1014    conda-forge
zstd                      1.5.2                ha9df2e0_1    conda-forge
```

and you can see that the version for `nbformat` is 5.1.3, which you can now add to the kernel json file.

**Comment by babreu-ncsa** [comment]
From the error it seems like the manager nodes are busy... I think I have an action running that might be blocking it, I'll clean it up and re-trigger provisioning

**Comment by babreu-ncsa** [comment]
It worked, so `nbformat` should be available now

**Pull request merged**
