### PR TITLE
MLTrainingJob

### PR DESCRIPTION
**Pull request by babreu-ncsa**
Implementation

### CODE REVIEW

**Comment by babreu-ncsa** [comment]
Looks like grabbing inputs and outputs is working.

**Comment by JamesCarzon** [comment]
@babreu-ncsa I am testing the new types I prototyped last week. For the JoinData type I would like to "train" the pipe with the simulation parameters table and "process" it with a table of simulation outputs, but currently I am failing to train the pipe due to a type error. (I am toying with it in [this notebook](https://tc02d-dev.c3dti.ai/jupyter/notebooks/research_teams/gordon/methods/Pipeline-test.ipynb#).)

I expect that there are a couple of ways of solving this problem, one of them designing the type to take arguments of the _FetchResult_ type as I've just tried; I am not sure yet why this does not work. The attached image shows the warning I receive when inputting the _SimulationModelParameters_ table. Another would be taking no input during training and fetching the input table inside the method anyway, but I would rather be able to specify the input in the event that new simulation runs are made available to me soon. Do you have a suggestion?
Screenshot 2022-06-20 194446

**Comment by babreu-ncsa** [comment]
@JamesCarzon I'm taking a look at this now... I think I understand what you are trying to do. 
In your `train` method you set a field `inputTable` of the JoinData type, but I don't see this field defined, so this will not work... Perhaps it will be better to discuss it over a call, do you have sometime this afternoon?

**Comment by JamesCarzon** [comment]
@babreu-ncsa I am free now until 5:00. I will send you a Zoom link by email.

**Comment by JamesCarzon** [comment]
Currently the JoinData type doesn't appear to have a method `getInputDataForSources`, which is confusing since this is one of the default methods for an MLDataSourceSpec of which JoinData is an extension.

**Comment by babreu-ncsa** [comment]
This seems to be working. Models are trained in parallel and saved to tables.

**Pull request merged**
